# Generated by Django 5.1.5 on 2025-01-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=50)),
                ('sales', models.IntegerField()),
            ],
        ),
    ]
