# Generated by Django 5.1.5 on 2025-04-07 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sellCycleLength', models.IntegerField(default=0)),
                ('avgOpportunitySize', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthsLeft', models.IntegerField(default=0)),
                ('yearToDateAttainment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('identifyRevenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qualifyRevenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('validateRevenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('proveRevenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('presentRevenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closeRevenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
