# Generated by Django 5.1.5 on 2025-04-08 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pipelinedata_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WinroomData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='')),
                ('responsible', models.CharField(blank=True, default='', max_length=255)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pipeline_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closed_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opportunity_gap', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pipeline_gap', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rowers_values', models.JSONField(blank=True, default=list)),
                ('activities', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winrooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
