# Generated by Django 5.1.5 on 2025-04-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_winroomdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='winroomdata',
            name='name',
            field=models.CharField(default='Unnamed Salesman', max_length=255),
        ),
        migrations.AddField(
            model_name='winroomdata',
            name='reviews',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
