directories:
  output: release
  buildResources: public
appId: com.itm8.salestool
files:
  - filter:
      - dist/**/*
      - '!node_modules/**/*'
extraResources:
  - filter:
      - public/*
mac:
  category: public.app-category.productivity
win:
  icon: public/logo.ico
linux:
  target: AppImage
  category: Utility
electronVersion: 34.2.0
