name: Build Mac

on:
  push:
    branches: ["main"]

jobs:
  buildMac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Build
        run: npm run build:electron
        working-directory: frontend

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mac-dmg
          path: frontend/release/*.dmg
